version: '3'
services:
  chapters-backend:
    build:
      context: ./src/
      args:
        SERVICE_PORT: ${SERVICE_PORT}
    image: wikitolearn/chapters-backend
    ports:
    - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
    - MONGO_HOST=${MONGO_HOST}
