version: '3.4'
services:
  chapters-backend:
    build:
      context: ./src/
      args:
        SERVICE_PORT: ${SERVICE_PORT}
    image: "${DOCKER_REGISTRY}wikitolearn/chapters-backend"
    ports:
    - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
    - MONGO_HOST=${MONGO_HOST}
